[package]
name = "daulric/retract"
version = "0.0.18"
description = "A declarative lua library for creating and managing roblox components"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]